# Generated by Django 4.1.6 on 2023-03-28 13:01

import colorfield.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='artist',
            name='color',
            field=colorfield.fields.ColorField(blank=True, default=None, image_field=None, max_length=18, null=True, samples=None),
        ),
        migrations.AddField(
            model_name='artist',
            name='cover',
            field=models.ImageField(default='a', upload_to='artist/covers/'),
            preserve_default=False,
        ),
    ]
