# Generated by Django 4.1.6 on 2023-03-28 13:01

import colorfield.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('song', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='playlist',
            name='color',
            field=colorfield.fields.ColorField(blank=True, default=None, image_field=None, max_length=18, null=True, samples=None),
        ),
    ]
